// Generated by npm run content:sync. Do not edit by hand.
import type { PortfolioPublicProjection } from "@/lib/public-content"

export const portfolioPublic = {
  "schemaVersion": 1,
  "generatedFrom": "career-docs public projection",
  "reviewedAt": "2026-07-21",
  "profile": {
    "name": "강태욱",
    "nameEn": "Kang Taewook",
    "role": "Product Engineer — AI Systems & Full-stack",
    "summary": "Grum과 TONE SEOUL 같은 사용자용 서비스를 인프라·웹·서버까지 풀스택으로 개발했습니다. 비정형 데이터를 구조화해 RAG·검색·추천에 연결하고, 담당자가 검토하는 업무 자동화 도구도 구현합니다.",
    "email": "woogi.dev@gmail.com",
    "github": "https://github.com/woogi-kang",
    "linkedin": "https://www.linkedin.com/in/taewook-kang/",
    "location": "Seoul, Korea",
    "image": "/profile.jpg"
  },
  "education": [
    {
      "institution": "계명대학교",
      "program": "게임모바일콘텐츠학과 학사 졸업",
      "period": "2014.09 - 2021.08"
    }
  ],
  "credentials": [
    {
      "name": "Google Cloud Associate Cloud Engineer",
      "detail": "자격 취득",
      "period": "2020.03"
    }
  ],
  "roleLenses": [
    {
      "id": "ai-product",
      "label": "AI 제품",
      "shortLabel": "AI",
      "summary": "웹과 이미지에서 정보를 모으고, 사람이 검토한 결과를 검색·추천·업무 도구에 연결한 사례입니다.",
      "caseOrder": [
        "grum-tone-seoul-fullstack-products",
        "human-governed-ai-operations",
        "woogi-harness",
        "structured-domain-data-pipeline",
        "domain-diagnostic-saas",
        "smart-glasses-realtime-platform",
        "ott-multiplatform-integration"
      ]
    },
    {
      "id": "product-fullstack",
      "label": "제품 구현",
      "shortLabel": "Product",
      "summary": "사용자 화면, API 서버, 데이터베이스와 클라우드 인프라를 한 제품 단위로 맡은 사례입니다.",
      "caseOrder": [
        "grum-tone-seoul-fullstack-products",
        "domain-diagnostic-saas",
        "human-governed-ai-operations",
        "structured-domain-data-pipeline",
        "woogi-harness",
        "ott-multiplatform-integration",
        "smart-glasses-realtime-platform"
      ]
    },
    {
      "id": "multiplatform-device",
      "label": "멀티플랫폼·디바이스",
      "shortLabel": "Device",
      "summary": "모바일·데스크톱·TV·스마트 글래스 사이의 연결, 복구와 현장 배포를 다룬 사례입니다.",
      "caseOrder": [
        "smart-glasses-realtime-platform",
        "ott-multiplatform-integration",
        "grum-tone-seoul-fullstack-products",
        "human-governed-ai-operations",
        "woogi-harness",
        "structured-domain-data-pipeline",
        "domain-diagnostic-saas"
      ]
    }
  ],
  "trajectory": [
    {
      "phase": "Device",
      "period": "2020—2022",
      "title": "모바일 제품과 배포 자동화",
      "body": "Flutter 앱에서 영상, 지도, 채팅 기능을 만들고 빌드와 배포 절차를 자동화했습니다.",
      "status": "context-only"
    },
    {
      "phase": "Product Delivery",
      "period": "2023—2025",
      "title": "멀티플랫폼 출시와 서비스 통합",
      "body": "OTT 통합과 스마트 디바이스 앱을 맡으며 사용자, 콘텐츠, DRM, 기기 통신의 의존 관계와 출시 일정을 조율했습니다.",
      "status": "context-only"
    },
    {
      "phase": "AI Systems",
      "period": "2025—Now",
      "title": "AI 제품과 AX 자동화의 풀스택 구현",
      "body": "Grum과 TONE SEOUL에서 인프라·웹·서버를 함께 개발하고, 데이터 수집과 RAG·검색·추천을 실제 사용자 서비스와 운영 도구에 연결했습니다.",
      "status": "context-only"
    }
  ],
  "cases": [
    {
      "slug": "grum-tone-seoul-fullstack-products",
      "title": "Grum · TONE SEOUL",
      "kicker": "플레드 · AI 건강상담·의료관광 제품",
      "period": "회사 제품",
      "role": "인프라 · 웹 · 서버 풀스택 개발",
      "domain": "AI 건강상담 · 피부과 탐색과 예약",
      "verificationMethod": "공개 서비스 · 저장소 이력",
      "summary": "사용자용 서비스 두 개를 인프라·웹·서버까지 풀스택으로 개발했습니다. Grum에서는 AI 건강상담의 웹·스트리밍 흐름을, TONE SEOUL에서는 다국어 피부과 탐색·예약 웹과 FastAPI 서버를 맡았습니다.",
      "problem": "AI 기능만 따로 만드는 것이 아니라 사용자 화면, API 서버, 데이터베이스와 배포 환경이 함께 움직이는 실제 서비스를 만들어야 했습니다.",
      "constraints": [
        "건강상담은 첨부파일과 이전 대화 맥락을 유지하면서 스트림 중단과 재연결을 처리해야 했습니다.",
        "병원과 시술 정보는 언어와 검색 조건이 달라도 같은 데이터 기준으로 탐색돼야 했습니다.",
        "웹·서버 배포와 인증, 데이터 구조와 API 계약을 함께 맞춰야 했습니다."
      ],
      "responsibility": [
        "Grum의 Flutter 핵심 기능을 Next.js 웹으로 전환하고 AI 상담 BFF·SSE 흐름 구현",
        "TONE SEOUL의 Next.js 사용자·운영 웹과 FastAPI 서버·도메인 로직 개발",
        "Grum의 RAG·혼합 검색·Tool Calling을 AI 상담 흐름에 연결",
        "TONE SEOUL의 PostgreSQL·Redis 데이터 계층과 GCP 배포 환경 구성",
        "두 제품의 인증·오류 처리·모니터링·배포 절차를 제품 흐름에 맞춰 정리"
      ],
      "decisions": [
        {
          "title": "AI 응답과 화면 상태를 한 스트림으로 다뤘습니다.",
          "body": "Grum 상담에서 텍스트 조각, UI 구성요소와 최종 데이터를 구분해 전달하고, 취소·복구와 추천 질문 상태를 같은 흐름에서 관리했습니다."
        },
        {
          "title": "검색 데이터와 생성 결과의 역할을 분리했습니다.",
          "body": "Grum에서는 RAG·혼합 검색·Tool Calling 결과를 상담 입력에 연결하고, 생성 응답과 화면 상태를 분리해 오류와 복구 흐름을 관리했습니다."
        },
        {
          "title": "웹·서버·인프라를 한 제품 범위로 판단했습니다.",
          "body": "화면 구현에서 끝내지 않고 API 계약, 데이터 저장과 배포 구성이 실제 사용자 흐름에서 함께 동작하는지 확인했습니다."
        }
      ],
      "implementation": [
        "Grum — Flutter 핵심 기능의 Next.js 전환, AI 상담 BFF·SSE와 Cloud Run 배포",
        "Grum — RAG·혼합 검색·Tool Calling을 상담 흐름에 연결",
        "TONE SEOUL — Next.js 사용자·운영 웹과 FastAPI 서버",
        "TONE SEOUL — PostgreSQL·Redis 데이터 계층",
        "TONE SEOUL — GCP Cloud Run·Cloud SQL·Cloud Storage·Secret Manager·Cloud Build 배포 구성"
      ],
      "validation": [
        {
          "text": "Grum 상담에서 첨부파일과 이전 대화 맥락을 유지하고, 응답 스트림의 취소·복구와 추천 질문 상태를 함께 처리했습니다.",
          "status": "verified",
          "claimIds": [
            "CLM-032"
          ]
        },
        {
          "text": "두 제품 모두 화면 구현에서 끝내지 않고 API 계약, 데이터 저장과 배포 환경까지 제품 단위로 맡았습니다.",
          "status": "context-only",
          "claimIds": [
            "CLM-031"
          ]
        }
      ],
      "outcomes": [
        {
          "text": "Grum과 TONE SEOUL에서 AI 기능과 사용자 화면, 서버, 데이터 계층과 배포 환경을 실제 서비스 흐름으로 연결했습니다.",
          "status": "context-only",
          "claimIds": [
            "CLM-031"
          ]
        }
      ],
      "evidence": [
        {
          "label": "Grum 공개 서비스",
          "kind": "screen",
          "detail": "AI 건강상담 제품의 공개 화면을 확인할 수 있습니다.",
          "href": "https://grum.co.kr/",
          "status": "verified"
        },
        {
          "label": "TONE SEOUL 공개 서비스",
          "kind": "screen",
          "detail": "다국어 피부과 탐색·예약 제품의 공개 화면을 확인할 수 있습니다.",
          "href": "https://tone-seoul.com/",
          "status": "verified"
        }
      ],
      "disclosure": {
        "status": "public",
        "note": "공개 서비스와 본인 작업 범위만 설명하며 비공개 코드, 고객 데이터와 운영 설정은 포함하지 않았습니다."
      },
      "diagram": {
        "caption": "두 제품에서 맡은 기술 범위 — 제품별 구성",
        "nodes": [
          "Grum: Next.js 웹",
          "Grum: BFF·SSE·RAG 연동",
          "제품별 분리",
          "TONE SEOUL: Next.js·FastAPI",
          "TONE SEOUL: PostgreSQL·Redis·GCP"
        ]
      },
      "lenses": [
        "ai-product",
        "product-fullstack"
      ],
      "seo": {
        "title": "Grum · TONE SEOUL — 인프라·웹·서버 풀스택 개발",
        "description": "AI 건강상담과 다국어 피부과 탐색·예약 서비스를 인프라·웹·서버까지 개발한 사례입니다.",
        "index": true
      }
    },
    {
      "slug": "woogi-harness",
      "title": "Woogi Harness",
      "kicker": "오픈소스 · AI 에이전트 운영",
      "period": "오픈소스",
      "role": "시스템 설계 · 운영",
      "domain": "AI 에이전트 운영",
      "verificationMethod": "GitHub 저장소 · 실행 명령",
      "summary": "Claude Code, Gemini CLI, Codex CLI, OpenCode가 같은 에이전트와 스킬을 쓰고, 프로젝트마다 필요한 지침만 골라 불러오도록 만든 오픈소스 하네스입니다.",
      "problem": "AI 에이전트와 스킬이 늘수록 작업에 맞는 기능을 고르기 어려워졌습니다. 여러 작업을 함께 실행할 때는 충돌을 막고 완료 여부를 같은 기준으로 판단해야 했습니다.",
      "constraints": [
        "Claude Code·Gemini CLI·Codex CLI·OpenCode에서 같은 원본을 사용해야 했습니다.",
        "긴 작업은 명령이 끝났다는 사실보다 테스트와 산출물로 완료 여부를 판단해야 했습니다.",
        "프로젝트 동기화는 대상 저장소의 기존 설정과 전용 파일을 보존해야 했습니다."
      ],
      "responsibility": [
        "기능 목록과 프로젝트 설정을 바탕으로 필요한 스킬을 고르는 구조 설계",
        "작업에 필요한 파일과 지침만 골라 불러오는 기능 구현",
        "성공 기준·중단 조건·승인 범위를 작업 시작 전에 기록하는 절차 도입",
        "여러 에이전트의 병렬 실행과 프로젝트별 안전한 설정 동기화 구성"
      ],
      "decisions": [
        {
          "title": "자산 수보다 선택 구조를 먼저 만들었습니다.",
          "body": "기능 목록에서 사용 가능한 자산을 찾고 프로젝트 설정이 필요한 지침만 선택하도록 해, 이름이 겹쳐도 추측으로 고르지 않게 했습니다."
        },
        {
          "title": "자율성보다 완료 판단을 명시했습니다.",
          "body": "명령 종료만으로 성공 처리하지 않고 테스트, 변경 내역, 로그, 브라우저 동작과 산출물이 있어야 완료로 판단하도록 설계했습니다."
        },
        {
          "title": "외부 도구에 보내는 자료를 먼저 검사했습니다.",
          "body": "외부 도구에 자료를 보내기 전에 포함할 파일과 분량을 정하고 비밀 정보 패턴을 검사했습니다."
        }
      ],
      "implementation": [
        "기능 목록·프로젝트 설정·작업별 파일 선택 기능",
        "작업 목표·허용 범위·완료 조건 기록",
        "DAG 기반 에이전트 병렬 실행",
        "manifest·backup·overlay 기반 프로젝트 동기화"
      ],
      "validation": [
        {
          "text": "GitHub 저장소에서 registry validation과 harness doctor 명령을 직접 실행할 수 있습니다.",
          "status": "verified",
          "claimIds": [
            "CLM-025"
          ]
        },
        {
          "text": "설치기 단위 테스트와 설정 오류를 찾는 정적 검사가 저장소에 포함돼 있습니다.",
          "status": "verified",
          "claimIds": [
            "CLM-025"
          ]
        }
      ],
      "outcomes": [
        {
          "text": "전문 에이전트 25개 이상과 skill entrypoint 385개를 네 AI CLI에서 함께 사용하고, 설정 오류는 실행 명령으로 확인할 수 있게 했습니다.",
          "status": "verified",
          "claimIds": [
            "CLM-025"
          ]
        }
      ],
      "evidence": [
        {
          "label": "GitHub 저장소",
          "kind": "repository",
          "detail": "코드, 실행 명령과 변경 이력을 확인할 수 있습니다.",
          "href": "https://github.com/woogi-kang/woogi-harness",
          "status": "verified"
        },
        {
          "label": "실행 명령",
          "kind": "command",
          "detail": "기능 목록 검사, 필요한 기능 선택, 지침 묶음 생성, 전체 상태 점검",
          "status": "verified"
        }
      ],
      "disclosure": {
        "status": "public",
        "note": "GitHub에서 코드와 실행 명령을 확인할 수 있습니다. 개인 프로젝트의 설정과 로그는 포함하지 않았습니다."
      },
      "diagram": {
        "caption": "프로젝트별 스킬 선택과 실행 흐름",
        "nodes": [
          "프로젝트 설정",
          "기능 목록",
          "필요한 파일·지침 선택",
          "작업 실행",
          "결과 확인"
        ]
      },
      "lenses": [
        "ai-product",
        "product-fullstack"
      ],
      "seo": {
        "title": "Woogi Harness — AI 에이전트 운영 하네스",
        "description": "네 AI CLI에서 에이전트와 스킬을 함께 쓰고 프로젝트별 설정을 안전하게 동기화한 오픈소스 프로젝트입니다.",
        "index": true
      }
    },
    {
      "slug": "structured-domain-data-pipeline",
      "title": "LLM 데이터 파이프라인",
      "kicker": "회사 프로젝트 · 데이터 수집과 검색",
      "period": "회사 프로젝트",
      "role": "제품 설계 · 풀스택 개발",
      "domain": "데이터 수집 · 검색",
      "verificationMethod": "코드 · 실행 문서",
      "summary": "웹페이지와 이미지에서 정보를 모아 같은 대상을 묶고, 형식과 가격·중복을 확인한 뒤 담당자가 승인한 값만 검색 데이터에 반영했습니다.",
      "problem": "웹과 이미지에서 가져온 정보는 출처와 형식이 제각각입니다. LLM 결과도 데이터 형식, 비용과 재시도 기준이 없으면 제품에 바로 쓰기 어렵습니다.",
      "constraints": [
        "입력 형태와 페이지 구조가 수집 대상마다 달랐습니다.",
        "일부 실패가 전체 실행을 다시 시작하게 만들면 비용과 운영 시간이 커집니다."
      ],
      "responsibility": [
        "수집 입력과 구조화 결과의 형식 설계",
        "이름·지역·위치 정보를 이용한 동일 대상 판별과 원문 링크 기록",
        "형식 검사·재시도·중간 저장·사용량 기록 구현",
        "자동 검사와 담당자 승인 뒤 표준 데이터와 검색 문서를 갱신하는 절차 정리"
      ],
      "decisions": [
        {
          "title": "LLM 응답을 바로 저장하지 않았습니다.",
          "body": "정해진 데이터 형식과 검사를 통과한 값만 다음 단계로 보내고, 실패 원인을 재시도 입력과 운영 기록에 남겼습니다."
        },
        {
          "title": "중간에 멈춰도 끝난 작업은 다시 하지 않게 했습니다.",
          "body": "단계별 체크포인트와 결과물을 남겨 중단된 지점에서 재개하고, 동일 입력의 중복 반영을 피할 수 있게 했습니다."
        },
        {
          "title": "수집과 동일 대상 판정을 분리했습니다.",
          "body": "페이지에서 값을 찾는 단계와 이름·지역·위치로 기존 엔터티를 맞추는 단계를 나누고, 원문·행·이미지 위치를 함께 기록해 사람이 판정을 다시 확인할 수 있게 했습니다."
        },
        {
          "title": "중요 값은 사람 검토 뒤 반영했습니다.",
          "body": "중복·가격·급격한 데이터 감소를 자동 검사하고, 운영자가 승인한 값만 표준 엔터티와 검색 데이터에 반영하도록 했습니다."
        }
      ],
      "implementation": [
        "웹·이미지·OCR·DOM 입력과 원문 링크 기록",
        "이름·지역·위치 기반 엔터티 매칭",
        "구조화 결과·형식·중복·가격 검사",
        "재시도·중간 저장·동시성·비용 기록",
        "담당자 승인 뒤 표준 데이터·검색 문서 갱신"
      ],
      "validation": [
        {
          "text": "URL 단위 진행 상태와 실패 사유를 남겨 중단된 작업을 이어서 실행할 수 있게 했습니다.",
          "status": "context-only",
          "claimIds": []
        },
        {
          "text": "중복·가격·급격한 데이터 감소를 자동으로 검사하고, 담당자가 승인한 값만 반영했습니다.",
          "status": "context-only",
          "claimIds": []
        }
      ],
      "outcomes": [
        {
          "text": "완료된 항목은 건너뛰고 남은 항목부터 수집을 이어갔으며, 담당자가 승인한 값만 표준 엔터티와 검색 문서에 반영했습니다.",
          "status": "context-only",
          "claimIds": []
        }
      ],
      "evidence": [
        {
          "label": "데이터 처리 흐름",
          "kind": "diagram",
          "detail": "수집부터 승인과 검색 반영까지의 주요 단계입니다.",
          "status": "context-only"
        }
      ],
      "disclosure": {
        "status": "anonymized",
        "note": "회사 프로젝트라 고객명과 원문 데이터는 제외하고, 제가 맡은 문제와 구현 범위만 정리했습니다."
      },
      "diagram": {
        "caption": "데이터 수집과 승인 흐름",
        "nodes": [
          "웹·이미지 입력",
          "같은 대상 찾기",
          "정보 추출",
          "검사·승인",
          "검색 데이터 반영"
        ]
      },
      "lenses": [
        "ai-product",
        "product-fullstack"
      ],
      "seo": {
        "title": "LLM 데이터 파이프라인 — Product Engineer 강태욱",
        "description": "웹과 이미지에서 정보를 수집해 검사·승인한 뒤 검색 데이터에 반영한 프로젝트입니다.",
        "index": true
      }
    },
    {
      "slug": "domain-diagnostic-saas",
      "title": "도메인 진단 SaaS",
      "kicker": "개인 프로젝트 · 진단 제품",
      "period": "개인 프로젝트",
      "role": "제품 설계 · 풀스택 개발",
      "domain": "B2B 진단 제품",
      "verificationMethod": "저장소 문서 · 코드",
      "summary": "외부 웹사이트를 수집해 7개 영역·48개 항목을 진단하고, 수집 실패와 실제 문제를 구분한 결과를 웹과 PDF로 제공했습니다.",
      "problem": "높은 평균 점수가 치명적 위험을 가리거나, 수집 실패가 낮은 품질로 오해되면 진단 제품의 신뢰가 무너집니다.",
      "constraints": [
        "외부 URL은 사설 네트워크 접근과 과도한 요청을 막아야 했습니다.",
        "AI가 만든 진단 결과는 출처, 모델 버전, 오류와 비용을 함께 기록해야 다시 확인할 수 있었습니다.",
        "웹 화면과 PDF에서 같은 판정 결과를 보여줘야 했습니다."
      ],
      "responsibility": [
        "URL 입력부터 수집·분석·점수화·리포트까지의 제품 흐름 설계",
        "HTTP 우선 수집과 SPA 징후가 있을 때의 브라우저 전환 구현",
        "측정 불가와 실제 실패의 분리, 핵심 위험 상한 규칙 구현",
        "URL·화면 캡처·신뢰도와 개선 우선순위 기준 정리"
      ],
      "decisions": [
        {
          "title": "총점보다 치명적 위험을 우선했습니다.",
          "body": "핵심 위험이 확인되면 다른 항목의 높은 점수가 이를 희석하지 않도록 점수 계산에 상한 원칙을 반영했습니다."
        },
        {
          "title": "측정 실패를 낮은 품질로 단정하지 않았습니다.",
          "body": "타임아웃·차단·외부 오류는 측정 불가로 분리하고, 확인하지 못한 사실을 낮은 점수처럼 보여주지 않았습니다."
        },
        {
          "title": "웹 화면과 PDF가 같은 판정 결과를 보여주게 했습니다.",
          "body": "결과를 보여줄 수 있는지 판단하는 함수를 함께 사용해 두 화면의 내용이 달라지지 않게 했습니다."
        },
        {
          "title": "브라우저 자동화는 필요한 페이지에만 사용했습니다.",
          "body": "먼저 HTTP 응답을 분석하고 SPA 징후나 렌더링 의존성이 있을 때만 브라우저 수집으로 전환해 비용과 실패 지점을 줄였습니다."
        },
        {
          "title": "점수 옆에 다음 작업을 남겼습니다.",
          "body": "URL·화면 캡처·신뢰도를 근거로 저장하고, 발견 항목을 영향도·수정 비용·담당 기준으로 정리해 보고서에서 바로 개선 순서를 확인할 수 있게 했습니다."
        }
      ],
      "implementation": [
        "Next.js 웹과 FastAPI 비동기 작업",
        "SSRF 방어·요청 제한·HTTP 우선 수집·조건부 브라우저 전환",
        "근거가 보이는 점수 계산과 측정 불가 처리",
        "URL·화면 캡처·신뢰도 기록",
        "영향도·수정 비용·담당 기준이 있는 웹·PDF 보고서"
      ],
      "validation": [
        {
          "text": "7개 영역·48개 항목의 진단 구조를 구현했습니다.",
          "status": "verified",
          "claimIds": [
            "CLM-006"
          ]
        },
        {
          "text": "점수 계산, 수집 안전성, AI 오류·예산과 웹·PDF 표시를 다루는 테스트 코드를 작성했습니다.",
          "status": "context-only",
          "claimIds": []
        }
      ],
      "outcomes": [
        {
          "text": "수집에 실패한 항목은 낮은 점수 대신 ‘측정 불가’로 표시하고, 발견 항목마다 URL·화면 캡처와 수정 우선순위를 붙였습니다.",
          "status": "context-only",
          "claimIds": [
            "CLM-006"
          ]
        }
      ],
      "evidence": [
        {
          "label": "진단 흐름",
          "kind": "diagram",
          "detail": "URL 입력부터 웹·PDF 결과까지의 주요 단계입니다.",
          "status": "context-only"
        }
      ],
      "disclosure": {
        "status": "anonymized",
        "note": "제품명과 실제 진단 대상은 제외했습니다. 구현한 진단 방식과 제가 맡은 범위를 설명합니다."
      },
      "diagram": {
        "caption": "진단과 보고서 생성 흐름",
        "nodes": [
          "URL 확인",
          "비동기 수집",
          "진단·점수 계산",
          "근거 기록",
          "웹·PDF 결과"
        ]
      },
      "lenses": [
        "product-fullstack",
        "ai-product"
      ],
      "seo": {
        "title": "도메인 진단 SaaS — Product Engineer 강태욱",
        "description": "외부 웹사이트를 7개 영역·48개 항목으로 진단하고 웹과 PDF 결과를 제공한 개인 프로젝트입니다.",
        "index": true
      }
    },
    {
      "slug": "human-governed-ai-operations",
      "title": "AI 작업 승인과 복구",
      "kicker": "개인 프로젝트 · AI 작업 관리",
      "period": "개인 프로젝트",
      "role": "제품 설계 · 풀스택 개발",
      "domain": "AI 작업 관리",
      "verificationMethod": "코드 · 운영 문서 · 로컬 프로토타입",
      "summary": "AI가 저장소나 외부 시스템을 바꾸기 전에 사용자가 목표와 수정 가능한 파일을 정하고 승인하며, 실행 뒤에는 변경 내역·로그·백업을 남기는 로컬 도구입니다.",
      "problem": "여러 AI 도구가 각자 작업을 실행하면 누가 무엇을 승인했는지, 허용된 범위를 벗어났는지, 실패 뒤 어디서 복구해야 하는지 한곳에서 확인하기 어렵습니다.",
      "constraints": [
        "모델이 승인되지 않은 목표나 쓰기 범위를 스스로 넓히지 못하게 해야 했습니다.",
        "저장소와 외부 시스템을 바꾸는 작업은 실행 전후 상태와 산출물을 남겨야 했습니다.",
        "저장소에 변경 중인 파일이 있거나 허용 범위를 벗어나면 실행을 멈춰야 했습니다."
      ],
      "responsibility": [
        "작업 목표·허용 범위·완료 상태 정의",
        "승인 ID·쓰기 범위·실행 작업의 경계 구현",
        "변경 내역·로그·산출물과 백업·복구 절차 연결"
      ],
      "decisions": [
        {
          "title": "모델과 실행 권한을 분리했습니다.",
          "body": "모델은 작업안을 만들고, 실행 단계에서 승인 ID와 쓰기 범위를 다시 확인한 뒤에만 실제 변경을 수행하도록 나눴습니다."
        },
        {
          "title": "기본값은 실제 파일을 바꾸지 않는 미리보기로 두었습니다.",
          "body": "기본 상태를 dry-run으로 두고 변경 중인 저장소나 허용 범위 밖 파일이 감지되면 실행을 멈추게 했습니다."
        },
        {
          "title": "완료 상태에 복구 자료를 포함했습니다.",
          "body": "명령 종료만으로 완료하지 않고 diff·로그·산출물과 백업 위치를 함께 기록해 검토와 되돌리기가 가능하게 했습니다."
        }
      ],
      "implementation": [
        "목표·입력·승인·쓰기 범위를 담은 작업 정의",
        "승인 대기와 실행 작업 분리",
        "허용 범위 밖 파일과 커밋하지 않은 변경이 있는 저장소에서 실행 차단",
        "실행 로그·산출물·변경 기록",
        "백업·복구 절차"
      ],
      "validation": [
        {
          "text": "AI가 변경을 실행하기 전에 승인 ID와 쓰기 범위를 다시 확인하도록 만들었습니다.",
          "status": "context-only",
          "claimIds": []
        },
        {
          "text": "실행 결과, 실패 지점과 백업 위치를 한 작업 기록에 남겼습니다.",
          "status": "context-only",
          "claimIds": []
        }
      ],
      "outcomes": [
        {
          "text": "작업 요청부터 승인, 실행과 재시도까지 한 화면에서 확인할 수 있는 로컬 프로토타입을 완성했습니다.",
          "status": "context-only",
          "claimIds": []
        }
      ],
      "evidence": [
        {
          "label": "작업 승인 흐름",
          "kind": "diagram",
          "detail": "작업 요청부터 승인, 실행과 복구까지의 주요 단계입니다.",
          "status": "context-only"
        }
      ],
      "disclosure": {
        "status": "anonymized",
        "note": "제품명과 실행 화면은 제외했습니다. 작업 승인과 복구 흐름을 중심으로 설명합니다."
      },
      "diagram": {
        "caption": "AI 작업 승인과 복구 흐름",
        "nodes": [
          "작업 요청",
          "사용자 승인",
          "실행 대기",
          "허용 범위 안에서 실행",
          "기록·복구"
        ]
      },
      "lenses": [
        "ai-product",
        "product-fullstack"
      ],
      "seo": {
        "title": "AI 작업 승인과 복구 — Product Engineer 강태욱",
        "description": "AI 작업의 목표와 수정 범위를 승인하고 실행 기록과 백업을 남기는 개인 프로젝트입니다.",
        "index": true
      }
    },
    {
      "slug": "smart-glasses-realtime-platform",
      "title": "스마트 글래스 실시간 플랫폼",
      "kicker": "회사 프로젝트 · 실시간 디바이스",
      "period": "회사 프로젝트",
      "role": "앱 플랫폼 설계 · 개발 리드",
      "domain": "실시간 멀티 디바이스 제품",
      "verificationMethod": "코드 · 테스트",
      "summary": "모바일·데스크톱·스마트 글래스가 함께 동작하는 실시간 오디오·자막 제품에서 BLE 메시지 전송, 연결 복구, 키오스크와 원격 업데이트 기능을 맡았습니다.",
      "problem": "BLE는 데이터를 작은 조각으로 나눠 보내야 했고, 순서가 바뀌거나 일부만 도착해도 다시 조립해야 했습니다. 네트워크가 끊긴 뒤에도 현장에서 복구할 수 있어야 했습니다.",
      "constraints": [
        "서로 다른 운영체제의 모바일·데스크톱·스마트 글래스 앱을 함께 다뤘습니다.",
        "BLE 전송은 작은 단위, 순서 변화와 부분 수신을 고려해야 했습니다."
      ],
      "responsibility": [
        "공통 패키지와 플랫폼 전용 경계 설계",
        "BLE 메시지 분할·재조립과 실시간 연결 복구 구현",
        "키오스크·네트워크 상태·원격 업데이트 등 현장 운영 기능 통합"
      ],
      "decisions": [
        {
          "title": "기기 통신을 화면 이벤트가 아닌 프로토콜로 다뤘습니다.",
          "body": "메시지 식별자·순번·전체 크기를 기준으로 데이터를 분할·재조립하고 순서 변화와 작은 전송 단위를 독립 테스트로 다뤘습니다."
        },
        {
          "title": "정상 연결과 재연결 로직을 분리했습니다.",
          "body": "연결 상태와 재연결 전략, 오디오 처리를 화면에서 떼어내 네트워크 변화가 제품 전체를 불안정하게 만들지 않도록 했습니다."
        },
        {
          "title": "현장 운영을 제품 기능으로 포함했습니다.",
          "body": "화면 유지, 네트워크·무음 상태, 키오스크와 업데이트를 운영자의 수동 체크에만 의존하지 않게 했습니다."
        }
      ],
      "implementation": [
        "여러 Flutter 앱이 함께 쓰는 공통 패키지",
        "BLE central·peripheral 메시지 전송",
        "WebSocket·오디오 연결 복구",
        "키오스크·기기 상태·원격 업데이트"
      ],
      "validation": [
        {
          "text": "메시지 분할·재조립, 역순 청크, 작은 전송 단위, 연결 상태와 오디오 변환을 다루는 테스트 코드를 작성했습니다.",
          "status": "context-only",
          "claimIds": [
            "CLM-003"
          ]
        }
      ],
      "outcomes": [
        {
          "text": "통신, 오디오와 현장 운영 코드를 화면에서 분리해 세 클라이언트가 같은 기반을 사용하도록 정리했습니다.",
          "status": "context-only",
          "claimIds": [
            "CLM-003"
          ]
        }
      ],
      "evidence": [
        {
          "label": "기기 연결 흐름",
          "kind": "diagram",
          "detail": "모바일 제어부터 현장 운영까지의 주요 단계입니다.",
          "status": "context-only"
        }
      ],
      "disclosure": {
        "status": "anonymized",
        "note": "회사 프로젝트라 제품명과 고객 정보는 제외하고, 제가 맡은 통신·복구·현장 운영 범위만 정리했습니다."
      },
      "diagram": {
        "caption": "기기 연결과 복구 흐름",
        "nodes": [
          "모바일 제어",
          "BLE 메시지",
          "실시간 연결",
          "글래스 화면",
          "현장 운영"
        ]
      },
      "lenses": [
        "multiplatform-device",
        "product-fullstack"
      ],
      "seo": {
        "title": "스마트 글래스 실시간 플랫폼 — Product Engineer 강태욱",
        "description": "모바일·데스크톱·스마트 글래스의 통신, 연결 복구와 현장 운영 기능을 구현한 회사 프로젝트입니다.",
        "index": true
      }
    },
    {
      "slug": "ott-multiplatform-integration",
      "title": "OTT 멀티플랫폼 통합",
      "kicker": "회사 프로젝트 · 서비스 통합",
      "period": "회사 프로젝트",
      "role": "멀티플랫폼 개발 · 통합 PM",
      "domain": "OTT 플랫폼 통합",
      "verificationMethod": "프로젝트 문서 · 수행 기록",
      "summary": "여러 사업자의 계정, VOD, DRM과 클라우드를 모바일·TV 앱 이전 일정과 함께 관리하고, 개발과 통합 PM을 함께 맡은 프로젝트입니다.",
      "problem": "계정, 콘텐츠 위치, DRM과 인증이 앱 일정과 맞물려 어느 한쪽이 늦어지면 로그인·재생·출시가 함께 밀릴 수 있었습니다.",
      "constraints": [
        "계정·콘텐츠·DRM·클라우드와 앱 전환 순서를 함께 관리해야 했습니다.",
        "모바일과 TV 플랫폼의 인증·재생 경험을 유지해야 했습니다."
      ],
      "responsibility": [
        "요청 파악과 기획·디자인 결과 확인",
        "사용자·VOD·DRM·클라우드·앱 작업의 의존 관계와 일정 조정",
        "멀티플랫폼 개발 전반의 통합 진행 관리"
      ],
      "decisions": [
        {
          "title": "앱 이전을 계정과 재생 준비에서 분리하지 않았습니다.",
          "body": "계정 데이터, VOD 위치, DRM과 인증 순서를 앱 개발 일정과 함께 관리해 화면 출시만 먼저 끝나는 상황을 피했습니다."
        },
        {
          "title": "직접 구현과 통합 조율의 역할을 구분했습니다.",
          "body": "앱에서 직접 구현한 기능과 계정·콘텐츠·재생·출시 일정을 조율한 역할을 나눠 관리했습니다."
        }
      ],
      "implementation": [
        "요구사항·기획·디자인 확인과 일정 조율",
        "계정·VOD·DRM·클라우드 의존 관계 정리",
        "모바일·TV 인증과 재생 흐름 통합",
        "단계별 이전과 출시 일정 조율"
      ],
      "validation": [
        {
          "text": "요구사항, 기획·디자인 결과와 플랫폼별 개발 일정을 하나의 의존 관계표로 관리했습니다.",
          "status": "context-only",
          "claimIds": [
            "CLM-023",
            "CLM-024"
          ]
        }
      ],
      "outcomes": [
        {
          "text": "계정·콘텐츠·DRM·클라우드·앱 전환 일정을 한 계획에서 관리했습니다.",
          "status": "context-only",
          "claimIds": [
            "CLM-023"
          ]
        }
      ],
      "evidence": [
        {
          "label": "서비스 통합 흐름",
          "kind": "diagram",
          "detail": "계정과 콘텐츠부터 모바일·TV 출시까지의 주요 단계입니다.",
          "status": "context-only"
        }
      ],
      "disclosure": {
        "status": "anonymized",
        "note": "회사 프로젝트라 고객명과 내부 일정은 제외하고, 제가 맡은 개발과 통합 PM 범위만 정리했습니다."
      },
      "diagram": {
        "caption": "OTT 전환 흐름",
        "nodes": [
          "계정",
          "콘텐츠·클라우드",
          "DRM·인증",
          "모바일·TV",
          "출시 계획"
        ]
      },
      "lenses": [
        "multiplatform-device",
        "product-fullstack"
      ],
      "seo": {
        "title": "OTT 멀티플랫폼 통합 — Product Engineer 강태욱",
        "description": "계정·콘텐츠·DRM·클라우드와 모바일·TV 앱 전환을 함께 조율한 회사 프로젝트입니다.",
        "index": true
      }
    }
  ],
  "withheldCases": [
    {
      "slug": "evidence-gated-ai-recommendation-pipeline",
      "title": "비공개 프로젝트",
      "reason": "소개할 수 있는 범위를 확인한 뒤 실제 역할과 결과를 중심으로 정리할 예정입니다."
    },
    {
      "slug": "self-improving-social-agents",
      "title": "비공개 프로젝트",
      "reason": "소개할 수 있는 범위를 확인한 뒤 실제 역할과 결과를 중심으로 정리할 예정입니다."
    }
  ],
  "legacyRedirects": [
    {
      "source": "/portfolio/internal-automation-agent-workflow",
      "destination": "/portfolio/woogi-harness"
    },
    {
      "source": "/portfolio/llm-structured-extraction-catalog-pipeline",
      "destination": "/portfolio/structured-domain-data-pipeline"
    },
    {
      "source": "/portfolio/data-collection-verification-pipeline",
      "destination": "/portfolio/structured-domain-data-pipeline"
    },
    {
      "source": "/portfolio/ai-product-quality-report-automation",
      "destination": "/portfolio/domain-diagnostic-saas"
    },
    {
      "source": "/portfolio/smart-glasses-platform-suite",
      "destination": "/portfolio/smart-glasses-realtime-platform"
    },
    {
      "source": "/portfolio/flutter-consulting-modernization",
      "destination": "/portfolio/ott-multiplatform-integration"
    }
  ],
  "experience": [
    {
      "period": "2026.01—2026.05",
      "organization": "주식회사 플레드",
      "role": "App Lead · AX Engineer",
      "summary": "Grum과 TONE SEOUL의 인프라·웹·서버를 풀스택으로 개발하고, RAG 기반 상담·검색과 병원·미용 데이터 수집, 운영 자동화를 실제 서비스에 연결했습니다.",
      "status": "context-only"
    },
    {
      "period": "2025",
      "organization": "스마트 디바이스 제품 조직",
      "role": "앱 개발 리드 · 개발 자동화",
      "summary": "멀티플랫폼 앱 기반과 실시간 기기 통신, 현장 운영 기능을 맡고 AI 도구를 사용하는 개발 절차를 정리했습니다.",
      "status": "context-only"
    },
    {
      "period": "2023—2025",
      "organization": "프로젝트 기반 제품 개발",
      "role": "Flutter 개발 · 프로젝트 리드",
      "summary": "OTT, 보안 문서, 실시간 제품의 현대화와 멀티플랫폼 확장을 맡았습니다. OTT 통합 프로젝트에서는 요구사항, 일정과 개발 의존 관계도 함께 조율했습니다.",
      "status": "context-only"
    },
    {
      "period": "2020—2022",
      "organization": "소비자 앱 개발 조직",
      "role": "Flutter 개발",
      "summary": "여행·성장관리·독서 커뮤니티 제품의 앱 전환, 핵심 기능과 배포 자동화를 구현했습니다.",
      "status": "context-only"
    }
  ],
  "skills": [
    {
      "label": "AI systems",
      "items": [
        "Structured output",
        "RAG & hybrid search",
        "Tool calling",
        "Evaluation",
        "Human review",
        "Agent workflow"
      ]
    },
    {
      "label": "Product delivery",
      "items": [
        "Next.js",
        "React",
        "Flutter",
        "FastAPI",
        "PostgreSQL",
        "Redis",
        "GCP Cloud Run",
        "Cloud SQL",
        "Cloud Storage",
        "Secret Manager",
        "Docker"
      ]
    },
    {
      "label": "Device & realtime",
      "items": [
        "BLE & GATT",
        "WebSocket",
        "Realtime audio",
        "Kiosk",
        "OTA",
        "Multi-platform release"
      ]
    }
  ],
  "roleDossiers": [
    {
      "slug": "alwayz-shopport-ai-data",
      "company": "Alwayz",
      "role": "Product Engineer · AI Data",
      "thesis": "형식이 제각각인 상품 정보를 출처와 검증 상태가 보이는 데이터로 정리하고, 검색·추천 기능에 반영한 경험을 모았습니다.",
      "existingEvidence": [
        {
          "text": "LLM 응답을 정해진 형식으로 받고 오류를 검사하며 다시 처리하는 데이터 파이프라인",
          "status": "context-only",
          "claimIds": []
        },
        {
          "text": "외부 입력의 실패와 측정 불가를 구분하는 제품 정책",
          "status": "context-only",
          "claimIds": []
        },
        {
          "text": "앱·웹·백엔드·운영 화면을 한 제품으로 구현한 경험",
          "status": "context-only",
          "claimIds": []
        }
      ],
      "futureProposal": [
        "상품 정보의 출처·신뢰도·갱신 상태를 먼저 모델링합니다.",
        "검색·추천에 반영하기 전 검사 기준과 담당자 승인 단계를 둡니다."
      ],
      "caseSlugs": [
        "structured-domain-data-pipeline",
        "domain-diagnostic-saas"
      ]
    },
    {
      "slug": "moais-ai-llm",
      "company": "MOAIS",
      "role": "AI · LLM Product Engineer",
      "thesis": "LLM 기능을 제품에 넣을 때 데이터 수집, 결과 검사, API와 오류 처리를 함께 설계한 경험을 정리했습니다.",
      "existingEvidence": [
        {
          "text": "LLM 응답을 정해진 형식으로 받고 규칙에 맞는지 검사",
          "status": "context-only",
          "claimIds": []
        },
        {
          "text": "검색과 도구 호출 결과에 출처와 실행 근거를 남긴 경험",
          "status": "context-only",
          "claimIds": []
        },
        {
          "text": "실패 지점·비용·검토 상태를 남기는 AI 작업 실행 도구",
          "status": "verified",
          "claimIds": [
            "CLM-025"
          ]
        }
      ],
      "futureProposal": [
        "현재 모델 출력과 실패 유형을 재현 가능한 평가 세트로 정리합니다.",
        "사람의 검토와 롤백이 필요한 경계를 제품 상태로 명시합니다."
      ],
      "caseSlugs": [
        "human-governed-ai-operations",
        "structured-domain-data-pipeline",
        "woogi-harness"
      ]
    },
    {
      "slug": "overdare-ai-agent",
      "company": "OVERDARE",
      "role": "AI Agent Product Engineer",
      "thesis": "제작 도구 안에서 AI가 맡은 작업을 사용자가 승인하고, 실행 과정을 확인하며, 실패하면 다시 이어갈 수 있게 설계한 경험을 정리했습니다.",
      "existingEvidence": [
        {
          "text": "Claude Code·Gemini CLI·Codex CLI·OpenCode가 같은 목표·완료 조건·승인 규칙을 따르도록 공통 작업 형식 설계",
          "status": "verified",
          "claimIds": [
            "CLM-025"
          ]
        },
        {
          "text": "전문 에이전트 25개 이상과 스킬 진입점 385개를 작업과 프로젝트에 맞춰 고르는 기능 구현",
          "status": "verified",
          "claimIds": [
            "CLM-025"
          ]
        },
        {
          "text": "여러 에이전트의 실행 순서·완료 확인·승인 범위와 프로젝트 설정 동기화 구현",
          "status": "verified",
          "claimIds": [
            "CLM-025"
          ]
        }
      ],
      "futureProposal": [
        "제작 작업을 계획·도구 호출·중간 산출물·검토·복구 상태로 나눕니다.",
        "사용자가 확인해야 하는 단계와 AI의 실행 과정·결과를 제품 화면에서 볼 수 있게 합니다."
      ],
      "caseSlugs": [
        "woogi-harness",
        "human-governed-ai-operations"
      ]
    },
    {
      "slug": "thefounders-fde",
      "company": "더파운더즈",
      "role": "Forward Deployed Engineer · AX",
      "thesis": "플레드에서 마케팅·운영팀이 손으로 처리하던 데이터 수집과 병원 문의 업무를 자동화했습니다. 이번 지원에서는 공개 리뷰를 직접 수집해 VOC Insight POC를 만들었습니다.",
      "liveDemo": {
        "label": "VOC Insight 데모 보기",
        "href": "https://voc-insight-demo-187813804164.asia-northeast3.run.app",
        "note": "오버뷰에서 원인 클러스터를 고르고, 리뷰 원문과 백로그까지 확인할 수 있습니다."
      },
      "metrics": [
        {
          "label": "병원 이벤트 자동화",
          "value": "3명·약 한 달 → 약 20시간",
          "note": "수집·검토·정리에 사람이 직접 투입한 시간"
        },
        {
          "label": "병원 데이터 수집",
          "value": "4,255행",
          "note": "네이버 플레이스 정보를 정리해 실제 업무에 적용"
        },
        {
          "label": "VOC 기준 리뷰",
          "value": "103,399건",
          "note": "원천 데이터 110,165행에서 반복된 6,766행 제외"
        },
        {
          "label": "한국어 번역",
          "value": "96,319건",
          "note": "한국어와 원문을 전환해 조회할 수 있는 리뷰"
        }
      ],
      "projectGroups": [
        {
          "id": "company-work",
          "eyebrow": "회사에서 수행",
          "title": "플레드에서 자동화한 세 가지 업무",
          "note": "반복 빈도와 투입 시간이 큰 업무를 골라 수집부터 서비스 반영까지 맡았습니다.",
          "projects": [
            {
              "name": "피부과 이벤트 수집 및 표준화 시스템",
              "meta": "플레드 · 마케팅·운영",
              "story": {
                "context": "마케팅·운영팀은 병원 홈페이지와 배너에서 이벤트명·시술·가격·기간을 직접 옮겨 적었습니다.",
                "problem": "약 4,000건의 이벤트가 여러 페이지와 이미지에 흩어져 있었고, 병원마다 표기가 달라 세 명이 약 한 달 동안 수집하고 정리해야 했습니다.",
                "build": "웹페이지와 배너를 수집해 OCR·LLM으로 구조화했습니다. 중복·비정상 가격·만료 이벤트를 걸러낸 뒤, 담당자가 원문과 결과를 확인하고 승인·반려하는 화면을 만들었습니다.",
                "result": "자동 수집과 서비스 반영을 네 차례 진행했습니다. 수집·검토·정리에 사람이 직접 투입한 시간은 총 약 20시간이었고, 반영 과정에서 발견한 오류와 예외도 수정했습니다."
              }
            },
            {
              "name": "전국 병원 네이버 플레이스 데이터 수집",
              "meta": "플레드 · 데이터 수집",
              "story": {
                "context": "병원 데이터에 진료시간·주차·예약·SNS·사진처럼 마케팅과 운영에 필요한 정보를 보강해야 했습니다.",
                "problem": "동명 병원과 여러 지점을 잘못 연결하지 않아야 했고, 전국 단위 수집이 중단돼도 완료된 작업을 보존해야 했습니다.",
                "build": "병원명·지역·도로명 주소·좌표를 차례로 비교해 실제 네이버 플레이스 페이지를 찾았습니다. 운영시간·주차·예약·SNS·사진이 있는 상세 영역을 수집하고, 체크포인트·재시도·결과 병합을 적용했습니다.",
                "result": "전국 병원 데이터 4,255행의 네이버 플레이스 정보를 수집해 서비스용으로 정리하고 실제 업무에 적용했습니다. CSV·JSON 결과와 진행 기록도 남겼습니다."
              }
            },
            {
              "name": "해외 환자 진료 조건 확인 자동화",
              "meta": "플레드 · 운영 자동화",
              "story": {
                "context": "운영팀은 병원마다 카카오톡으로 외국인 환자 진료 가능 여부를 확인하고 답변을 다시 정리했습니다.",
                "problem": "여러 계정이 문의를 나눠 처리해 누락, 중복 발송, 허용 시간대 밖 발송이 생기기 쉬웠습니다.",
                "build": "문의 발송, 새 답장 확인, 내용 분류, 상태 기록을 자동화했습니다. 정해진 답변은 템플릿으로 처리하고, 제안서·계약처럼 판단이 필요한 대화는 담당자에게 넘겼습니다.",
                "result": "병원별 문의·회신 상태와 답변 근거를 정리해 담당자가 확인한 뒤 서비스에 반영할 수 있게 했습니다."
              }
            }
          ]
        },
        {
          "id": "role-proof",
          "eyebrow": "개인 POC",
          "title": "공개 리뷰를 원인별로 묶은 VOC Insight",
          "note": "더파운더즈에서 데이터를 제공받지 않았습니다. 여러 판매 채널의 공개 리뷰를 직접 수집해 만든 개인 POC입니다.",
          "projects": [
            {
              "name": "VOC Insight",
              "meta": "개인 프로젝트",
              "story": {
                "context": "브랜드와 판매 채널이 늘수록 실무자가 다국어 리뷰를 모두 읽고 반복 원인과 우선순위를 찾기 어렵습니다.",
                "problem": "리뷰마다 언어와 출처가 달랐고, 같은 원인을 말하는 리뷰도 흩어져 있어 우선순위를 정하기 어려웠습니다.",
                "build": "원문·평점·작성일·상품·채널·출처 링크를 보존하고, 오버뷰·원인 클러스터·상세 통계·백로그·원문 탐색 화면으로 연결했습니다.",
                "result": "1·2점 리뷰 610건마다 분류 결과나 제외 사유를 남겼습니다. 분석 대상은 같은 원인이나 현상별로 묶고 원문 근거를 붙였으며, 안전 관련 표현은 담당자가 확인할 검토 후보로 분리했습니다."
              }
            }
          ]
        }
      ],
      "fitMap": {
        "eyebrow": "업무 연결",
        "title": "지원 역할과 맞닿은 세 가지 경험",
        "note": "실제 데이터와 담당자의 업무 흐름을 확인한 뒤 작은 범위부터 시작합니다.",
        "items": [
          {
            "workstream": "글로벌 리뷰와 경쟁사 데이터",
            "evidence": "플레드에서 병원 이벤트와 네이버 플레이스 데이터를 수집해 실제 업무에 적용했습니다. VOC Insight에서는 원문과 분석 결과를 이어서 확인하도록 만들었습니다.",
            "firstCheck": "사용할 수 있는 데이터, 추가 권한이 필요한 데이터, 갱신 주기를 먼저 구분합니다."
          },
          {
            "workstream": "인플루언서·파트너 문의 운영",
            "evidence": "병원 문의 업무에서 발송, 회신 분류, 중복 방지, 담당자 인계를 구현했습니다.",
            "firstCheck": "한 시장과 한 캠페인에서 대상 선정, 승인, 회신 분류, 담당자 인계 기준부터 정합니다."
          },
          {
            "workstream": "마케팅·MD 검토 화면",
            "evidence": "이벤트 검토 화면과 VOC Insight에서 원문, 오류, 우선순위, 다음 행동을 한 화면에 모았습니다.",
            "firstCheck": "담당자가 가장 자주 내리는 결정 하나부터 처리 시간과 수정 횟수를 비교합니다."
          }
        ]
      },
      "proposalSection": {
        "eyebrow": "합류 후",
        "title": "한 가지 업무부터 함께 바꾸겠습니다",
        "note": "시간과 오류가 실제로 줄어드는지 확인한 뒤 다음 업무로 넓힙니다."
      },
      "futureProposal": [
        "담당자와 실제 업무 흐름을 살펴보고, 반복해서 찾고 옮기는 일을 고릅니다.",
        "효과를 빨리 확인할 수 있는 한 가지를 골라 예외와 승인 기준까지 함께 정합니다.",
        "시간과 오류가 줄었는지 확인한 뒤, 효과가 있었던 방식만 다음 업무에 적용합니다."
      ]
    }
  ]
} as const satisfies PortfolioPublicProjection
