import { mkdir, readFile, writeFile } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const sourcePath = resolve(
  process.env.PORTFOLIO_PUBLIC_SOURCE ??
    resolve(projectRoot, "../career-docs/exports/portfolio-public.json"),
)
const jsonTarget = resolve(projectRoot, "content/portfolio-public.json")
const tsTarget = resolve(projectRoot, "content/portfolio-public.generated.ts")

const source = JSON.parse(await readFile(sourcePath, "utf8"))
const serialized = `${JSON.stringify(source, null, 2)}\n`
const generated = `// Generated by npm run content:sync. Do not edit by hand.\nimport type { PortfolioPublicProjection } from "@/lib/public-content"\n\nexport const portfolioPublic = ${JSON.stringify(source, null, 2)} as const satisfies PortfolioPublicProjection\n`

await mkdir(dirname(jsonTarget), { recursive: true })
await writeFile(jsonTarget, serialized)
await writeFile(tsTarget, generated)

console.log(`Synced public portfolio content from ${sourcePath}`)
